package agent

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Markers for the AGENTS.md mirror inside a global CLAUDE.md.
//
// A separate pair from ManagedImportBlockStart/End so the two managed
// regions can coexist and be regenerated independently. Content
// outside both pairs is preserved.
const (
	AgentsMDBlockStart = "<!-- sync-agents:agents-md:start -->"
	AgentsMDBlockEnd   = "<!-- sync-agents:agents-md:end -->"
)

const agentsMDBanner = "<!-- mirrored from AGENTS.md by sync-agents; edit AGENTS.preamble.md, not this block -->"

// ResolveGlobalAgentsMDPath returns the absolute path of the AGENTS.md
// that belongs to the global agents tree, or "" when it cannot be
// located.
//
// The global root is conventionally a symlink (~/.agents ->
// <repo>/.agents), and AGENTS.md lives in the repo that owns the tree —
// one level above the resolved .agents directory, NOT above the
// symlink. Resolving lexically would look for AGENTS.md next to the
// symlink (e.g. $HOME/AGENTS.md) and silently find nothing, so the
// symlink is resolved first.
func ResolveGlobalAgentsMDPath(globalRoot string) string {
	resolved, err := filepath.EvalSymlinks(globalRoot)
	if err != nil {
		resolved = globalRoot
	}
	candidate := filepath.Join(filepath.Dir(resolved), "AGENTS.md")
	if _, err := os.Stat(candidate); err != nil {
		return ""
	}
	return candidate
}

// agentsRelativeLinkRegexp matches markdown links whose target is
// relative to the agents repo root, e.g. `](.agents/rules/x.md)`.
var agentsRelativeLinkRegexp = regexp.MustCompile(`\]\(\.agents/`)

// AbsolutizeAgentsMDLinks rewrites repo-relative links in AGENTS.md so
// they still resolve once the content is mirrored into a CLAUDE.md that
// lives somewhere else.
//
// AGENTS.md indexes artifacts as `](.agents/rules/x.md)`, which is
// correct relative to the agents repo. Copied verbatim into
// ~/.claude/CLAUDE.md those become ~/.claude/.agents/rules/x.md, which
// does not exist — every index link would dangle.
//
// The rewrite targets the REAL directory, dropping the `.agents/`
// segment: `.agents/rules`, `.agents/skills`, and `.agents/workflows`
// are all symlinks to `../rules`, `../skills`, and `../workflows`, so
// `<root>/rules/x.md` and `<root>/.agents/rules/x.md` are the same file
// — but only the former is reachable without following a symlink.
//
// That difference is not cosmetic. Editors that decline to traverse
// symlinks (VS Code with `search.followSymlinks: false`, for one)
// report the `.agents/` form as a missing file and offer to create it,
// even though the target exists. Linking through the real path makes
// the index work regardless of how the reader treats symlinks, and
// points at the source of truth rather than the generated overlay.
func AbsolutizeAgentsMDLinks(content, agentsRepoRoot string) string {
	return agentsRelativeLinkRegexp.ReplaceAllString(
		content,
		"]("+agentsRepoRoot+string(filepath.Separator),
	)
}

// BuildAgentsMDBlock renders the managed AGENTS.md mirror block.
// stripGeneratorPreamble removes the YAML frontmatter and the
// provenance banner from AGENTS.md content before it is mirrored
// into CLAUDE.md.
//
// Both are addressed to readers of AGENTS.md: the frontmatter carries
// a trigger key for tools that use one, and the banner says which
// command regenerates the file. CLAUDE.md is loaded as always-on
// context in every session, so neither earns its place there, and the
// banner's instruction is actively wrong for it — regenerating
// CLAUDE.md is not what `sync-agents index` does.
//
// Only the mirror is affected. AGENTS.md keeps both.
func stripGeneratorPreamble(content string) string {
	// Leading `---` ... `---` frontmatter block.
	if strings.HasPrefix(content, "---\n") {
		if end := strings.Index(content[4:], "\n---\n"); end >= 0 {
			content = content[4+end+len("\n---\n"):]
		}
	}

	// Lines the generator writes for readers of AGENTS.md. Each is
	// matched exactly: anything the author wrote is content and must
	// survive, including blockquotes.
	var out []string
	for _, line := range strings.Split(content, "\n") {
		t := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(t, "> Auto-generated by"):
			continue
		case strings.HasPrefix(t, "> Run `sync-agents index`"):
			continue
		case t == "# AGENTS":
			continue
		case t == "This file indexes all rules, skills, and workflows defined in `.agents/`.":
			continue
		case t == PreambleMarker:
			continue
		}
		out = append(out, line)
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}

func BuildAgentsMDBlock(agentsMDContent, agentsRepoRoot string) string {
	var buf bytes.Buffer
	buf.WriteString(AgentsMDBlockStart)
	buf.WriteString("\n")
	buf.WriteString(AbsolutizeAgentsMDLinks(stripGeneratorPreamble(agentsMDContent), agentsRepoRoot))
	if !bytes.HasSuffix(buf.Bytes(), []byte("\n")) {
		buf.WriteString("\n")
	}
	buf.WriteString(AgentsMDBlockEnd)
	buf.WriteString("\n")
	return buf.String()
}

// RegenerateAgentsMDBlock mirrors the global AGENTS.md into claudeMDPath
// as a managed block, reporting whether the file changed.
//
// Returns (false, nil) when there is no AGENTS.md to mirror — the
// feature is opt-in and its absence is not an error, exactly as a
// missing preamble is not.
func RegenerateAgentsMDBlock(claudeMDPath, agentsMDPath string) (bool, error) {
	if agentsMDPath == "" {
		return false, nil
	}
	raw, err := os.ReadFile(agentsMDPath)
	if err != nil {
		return false, err
	}

	newBlock := BuildAgentsMDBlock(string(raw), filepath.Dir(agentsMDPath))

	existing, readErr := os.ReadFile(claudeMDPath)
	var out string
	if readErr != nil {
		out = newBlock
	} else {
		out = replaceBlockBetweenMarkers(string(existing), newBlock, AgentsMDBlockStart, AgentsMDBlockEnd)
		if out == string(existing) {
			return false, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(claudeMDPath), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(claudeMDPath, []byte(out), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// BucketLinkPrefix returns the path prefix to use when the generated
// AGENTS.md index links a bucket's artifacts.
//
// Normally that is `.agents/<bucket>`, because `sync-agents init`
// creates those as real directories and the artifacts genuinely live
// there.
//
// The agents repo inverts this: the real `rules/`, `skills/`, and
// `workflows/` sit at the project root and `.agents/<bucket>` is a
// symlink pointing back at them (ADR-001). Both paths reach the same
// file, but the `.agents/` one only via a symlink — and readers that
// decline to follow symlinks (VS Code with `search.followSymlinks:
// false`) then report every index link as a missing file.
//
// So when the bucket is a symlink resolving inside the project, link
// the resolved location instead. Anything else — a real directory, an
// unreadable path, or a link escaping the project — keeps the
// `.agents/` form, which is correct for the normal layout.
func BucketLinkPrefix(projectRoot, agentsDir, bucket string) string {
	fallback := ".agents/" + bucket

	info, err := os.Lstat(filepath.Join(agentsDir, bucket))
	if err != nil || info.Mode()&os.ModeSymlink == 0 {
		return fallback
	}

	resolved, err := filepath.EvalSymlinks(filepath.Join(agentsDir, bucket))
	if err != nil {
		return fallback
	}
	root, err := filepath.EvalSymlinks(projectRoot)
	if err != nil {
		root = projectRoot
	}

	rel, err := filepath.Rel(root, resolved)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(rel) {
		// Escapes the project — a relative link would not resolve.
		return fallback
	}
	return filepath.ToSlash(rel)
}
